name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          build: yarn run build
          start: yarn run start

      # - name: Run Component tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     config-file: cypress.component.json
      #     # we have already installed everything
      #     install: false
      #     # to run component tests we need to use "cypress run-ct"
      #     command: yarn run cypress:ct:headless
