name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run components
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.component.json
      - name: Cypress run e2e
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.e2e.json
          build: yarn run build
          start: yarn run start
